services:
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always
    networks: [backend]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  web-api:
    build: ./apps/web-api
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WEB_API_PORT: ${WEB_API_PORT}
    ports:
      - "${WEB_API_PORT}:3001"
    restart: always
    networks: [backend, frontend]

  web-frontend:
    build: ./apps/web-frontend
    env_file: .env
    environment:
      INTERNAL_WEB_API_URL: http://web-api:3000
    ports:
      - "${WEB_FRONTEND_PORT}:3000"
    networks: [frontend]

  admin-api:
    build: ./apps/admin-api
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_API_PORT: ${ADMIN_API_PORT}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "${ADMIN_API_PORT}:3001"
    networks: [backend, frontend]

  admin-frontend:
    build: ./apps/admin-frontend
    env_file: .env
    environment:
      INTERNAL_ADMIN_API_URL: http://admin-api:3000
    ports:
      - "${ADMIN_FRONTEND_PORT}:3000"
    networks: [frontend]

networks:
  frontend:
  backend:

volumes:
  pgdata:
  pgadmin:
